var simplemaps_countrymap_mapdata = {
  main_settings: {
    // General settings
    width: "responsive", // or 'responsive'
    background_color: "#FFFFFF",
    background_transparent: "yes",
    border_color: "#ffffff",
    pop_ups: "detect",

    // State defaults
    state_description: "State description",
    state_color: "#88A4BC",
    state_hover_color: "#3B729F",
    state_url: "",
    border_size: 1.5,
    all_states_inactive: "no",
    all_states_zoomable: "yes",

    // Location defaults
    location_description: "Location description",
    location_url: "",
    location_color: "#FF0067",
    location_opacity: 0.8,
    location_hover_opacity: 1,
    location_size: 25,
    location_type: "square",
    location_image_source: "frog.png",
    location_border_color: "#FFFFFF",
    location_border: 2,
    location_hover_border: 2.5,
    all_locations_inactive: "no",
    all_locations_hidden: "no",

    // Label defaults
    label_color: "#ffffff",
    label_hover_color: "#ffffff",
    label_size: 16,
    label_font: "Arial",
    label_display: "auto",
    label_scale: "yes",
    hide_labels: "no",
    hide_eastern_labels: "no",

    // Zoom settings
    zoom: "yes",
    manual_zoom: "yes",
    back_image: "no",
    initial_back: "no",
    initial_zoom: "-1",
    initial_zoom_solo: "no",
    region_opacity: 1,
    region_hover_opacity: 0.6,
    zoom_out_incrementally: "yes",
    zoom_percentage: 0.99,
    zoom_time: 0.5,

    // Popup settings
    popup_color: "white",
    popup_opacity: 0.9,
    popup_shadow: 1,
    popup_corners: 5,
    popup_font: "12px/1.5 Verdana, Arial, Helvetica, sans-serif",
    popup_nocss: "no",

    // Advanced settings
    div: "map",
    auto_load: "yes",
    url_new_tab: "no",
    images_directory: "default",
    fade_time: 0.1,
    link_text: "View Website",
  },
  state_specific: {
    USA01: {
      name: "Alabama",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA02: {
      name: "Alaska",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA03: {
      name: "Arizona",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA04: {
      name: "Arkansas",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA05: {
      name: "California",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA06: {
      name: "Colorado",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA07: {
      name: "Connecticut",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA08: {
      name: "Delaware",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA09: {
      name: "Florida",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA10: {
      name: "Georgia",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA11: {
      name: "Hawaii",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA12: {
      name: "Idaho",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA13: {
      name: "Illinois",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA14: {
      name: "Indiana",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA15: {
      name: "Iowa",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA16: {
      name: "Kansas",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA17: {
      name: "Kentucky",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA18: {
      name: "Louisiana",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA19: {
      name: "Maine",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA20: {
      name: "Maryland",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA21: {
      name: "Massachusetts",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA22: {
      name: "Michigan",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA23: {
      name: "Minnesota",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA24: {
      name: "Mississippi",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA25: {
      name: "Missouri",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA26: {
      name: "Montana",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA27: {
      name: "Nebraska",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA28: {
      name: "Nevada",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA29: {
      name: "New Hampshire",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA30: {
      name: "New Jersey",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA31: {
      name: "New Mexico",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA32: {
      name: "New York",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA33: {
      name: "North Carolina",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA34: {
      name: "North Dakota",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA35: {
      name: "Ohio",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA36: {
      name: "Oklahoma",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA37: {
      name: "Oregon",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA38: {
      name: "Pennsylvania",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA39: {
      name: "Rhode Island",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA40: {
      name: "South Carolina",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA41: {
      name: "South Dakota",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA42: {
      name: "Tennessee",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA43: {
      name: "Texas",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA44: {
      name: "Utah",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA45: {
      name: "Vermont",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA46: {
      name: "Virginia",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA47: {
      name: "Washington",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA48: {
      name: "West Virginia",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA49: {
      name: "Wisconsin",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA50: {
      name: "Wyoming",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
    USA51: {
      name: "District of Columbia",
      description: "default",
      color: "default",
      hover_color: "default",
      url: "default",
    },
  },
  locations: {
    "0": {
      name: "Washington, D.C.",
      lat: "38.89511",
      lng: "-77.03637",
    },
  },
  labels: {
    USA01: {
      name: "Alabama",
      parent_id: "USA01",
    },
    USA02: {
      name: "Alaska",
      parent_id: "USA02",
    },
    USA03: {
      name: "Arizona",
      parent_id: "USA03",
    },
    USA04: {
      name: "Arkansas",
      parent_id: "USA04",
    },
    USA05: {
      name: "California",
      parent_id: "USA05",
    },
    USA06: {
      name: "Colorado",
      parent_id: "USA06",
    },
    USA07: {
      name: "Connecticut",
      parent_id: "USA07",
    },
    USA08: {
      name: "Delaware",
      parent_id: "USA08",
    },
    USA09: {
      name: "Florida",
      parent_id: "USA09",
    },
    USA10: {
      name: "Georgia",
      parent_id: "USA10",
    },
    USA11: {
      name: "Hawaii",
      parent_id: "USA11",
    },
    USA12: {
      name: "Idaho",
      parent_id: "USA12",
    },
    USA13: {
      name: "Illinois",
      parent_id: "USA13",
    },
    USA14: {
      name: "Indiana",
      parent_id: "USA14",
    },
    USA15: {
      name: "Iowa",
      parent_id: "USA15",
    },
    USA16: {
      name: "Kansas",
      parent_id: "USA16",
    },
    USA17: {
      name: "Kentucky",
      parent_id: "USA17",
    },
    USA18: {
      name: "Louisiana",
      parent_id: "USA18",
    },
    USA19: {
      name: "Maine",
      parent_id: "USA19",
    },
    USA20: {
      name: "Maryland",
      parent_id: "USA20",
    },
    USA21: {
      name: "Massachusetts",
      parent_id: "USA21",
    },
    USA22: {
      name: "Michigan",
      parent_id: "USA22",
    },
    USA23: {
      name: "Minnesota",
      parent_id: "USA23",
    },
    USA24: {
      name: "Mississippi",
      parent_id: "USA24",
    },
    USA25: {
      name: "Missouri",
      parent_id: "USA25",
    },
    USA26: {
      name: "Montana",
      parent_id: "USA26",
    },
    USA27: {
      name: "Nebraska",
      parent_id: "USA27",
    },
    USA28: {
      name: "Nevada",
      parent_id: "USA28",
    },
    USA29: {
      name: "New Hampshire",
      parent_id: "USA29",
    },
    USA30: {
      name: "New Jersey",
      parent_id: "USA30",
    },
    USA31: {
      name: "New Mexico",
      parent_id: "USA31",
    },
    USA32: {
      name: "New York",
      parent_id: "USA32",
    },
    USA33: {
      name: "North Carolina",
      parent_id: "USA33",
    },
    USA34: {
      name: "North Dakota",
      parent_id: "USA34",
    },
    USA35: {
      name: "Ohio",
      parent_id: "USA35",
    },
    USA36: {
      name: "Oklahoma",
      parent_id: "USA36",
    },
    USA37: {
      name: "Oregon",
      parent_id: "USA37",
    },
    USA38: {
      name: "Pennsylvania",
      parent_id: "USA38",
    },
    USA39: {
      name: "Rhode Island",
      parent_id: "USA39",
    },
    USA40: {
      name: "South Carolina",
      parent_id: "USA40",
    },
    USA41: {
      name: "South Dakota",
      parent_id: "USA41",
    },
    USA42: {
      name: "Tennessee",
      parent_id: "USA42",
    },
    USA43: {
      name: "Texas",
      parent_id: "USA43",
    },
    USA44: {
      name: "Utah",
      parent_id: "USA44",
    },
    USA45: {
      name: "Vermont",
      parent_id: "USA45",
    },
    USA46: {
      name: "Virginia",
      parent_id: "USA46",
    },
    USA47: {
      name: "Washington",
      parent_id: "USA47",
    },
    USA48: {
      name: "West Virginia",
      parent_id: "USA48",
    },
    USA49: {
      name: "Wisconsin",
      parent_id: "USA49",
    },
    USA50: {
      name: "Wyoming",
      parent_id: "USA50",
    },
    USA51: {
      name: "District of Columbia",
      parent_id: "USA51",
    },
  },
};
